use crate::account::{AccountData, AssetContext, WalletDetailsData, WalletTrackerSnapshot};
use crate::account_analytics::{IncomeSnapshot, PortfolioHistory};
use crate::account_state::{BottomTab, PositionsSortColumn};
use crate::annotations::{Annotation, AnnotationId, DrawingTool};
use crate::api::{self, Candle, ExchangeSymbol, OrderBook};
use crate::calendar_state::{CalendarImpactFilter, CalendarWindowFilter};
use crate::chart::ChartViewport;
use crate::chart_state::{CandleFetchRequest, ChartId, FundingFetchRequest};
use crate::config;
use crate::hydromancer_api::FundingRatePoint;
use crate::hyperdash_api::{LiquidationHeatmap, LiquidationLevel};
use crate::journal;
use crate::market_state::{
    LiveWatchlistId, OrderBookId, OrderBookSymbolMode, SymbolSearchMarketFilter,
    SymbolSearchSortMode,
};
use crate::pane_management::AddWidgetPlacement;
use crate::portfolio_state::{PortfolioScope, PortfolioWindow};
use crate::settings_state::SettingsTab;
use crate::signing::{ExchangeResponse, OrderKind};
use crate::spaghetti;
use crate::spaghetti_state::{SpaghettiCandleFetch, SpaghettiChartId};
use crate::timeframe::Timeframe;
use crate::ws::WsUserData;
use iced::widget::pane_grid;
use iced::{Point, Size, window};
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    SaveLayout(String),
    LoadLayout(config::SavedLayout),
    DeleteLayout(String),
    ExportLayout(config::SavedLayout),
    ImportLayout,
    LayoutImported(Result<config::SavedLayout, String>),
    LayoutExported(Result<(), String>),
    ExportWalletLabels,
    ImportWalletLabels,
    WalletLabelsExported(Result<(), String>),
    WalletLabelsImported(Result<config::WalletLabelsExport, String>),
    LayoutInputChanged(String),
    LiveWatchlistSearchChanged(LiveWatchlistId, String),
    LiveWatchlistContextsLoaded(
        u64,
        Result<HashMap<String, crate::api::WatchlistContext>, String>,
    ),
    LiveWatchlistHistoryLoaded(
        Vec<String>,
        u64,
        Result<HashMap<String, (f64, f64, f64)>, String>,
    ),
    LiveWatchlistAddSymbol(LiveWatchlistId, String),
    LiveWatchlistRemoveSymbol(LiveWatchlistId, String),
    LiveWatchlistRefreshTick,
    LiveWatchlistSortChanged(LiveWatchlistId, config::LiveWatchlistSortColumn),
    LiveWatchlistColumnToggled(LiveWatchlistId, config::LiveWatchlistColumn, bool),
    AddLiveWatchlistPane,
    AddOrderBookPane,
    PositionsSortChanged(PositionsSortColumn),

    ToggleAccountPicker,
    AccountPickerSelected(usize),
    AccountLabelChanged(String),
    AddAccount,
    GhostWallet(String),
    ForgetGhostAccount(usize),
    SaveCredentials,
    PaneResized(pane_grid::ResizeEvent),
    PaneDragged(pane_grid::DragEvent),
    PaneClicked(pane_grid::Pane),
    SwitchBottomTab(BottomTab),
    OrderPriceChanged(String),
    SetMidPrice,
    OrderQuantityChanged(String),
    SetOrderKind(OrderKind),
    ToggleOrderDenomination,
    OrderPercentageChanged(f32),
    ToggleReduceOnly,
    TogglePresetsMenu,
    TogglePresetCurrency,
    TogglePresetEditMode,
    SetAddWidgetPlacement(AddWidgetPlacement),
    EditPresetStart(crate::signing::OrderKind, usize, String),
    EditPresetChanged(String),
    EditPresetSave(crate::signing::OrderKind, usize),
    ExecutePreset(crate::signing::OrderKind, crate::config::OrderPreset, bool),
    ToggleFavourite(String),
    // Add widget menu
    ToggleAddWidgetMenu,
    ToggleMacroMenu(ChartId),
    ToggleMacroIndicator(ChartId, String),
    CloseAllMenus,
    AddPortfolioPane,
    AddIncomePane,
    AddComparisonChart,
    AddPairRatioChart,
    OpenSettingsWindow,
    SettingsTabSelected(SettingsTab),
    OpenUnlockCredentialsPopup,
    DismissUnlockCredentialsPopup,
    OpenCredentialStorageSettings,
    SecretStorageSelectionChanged(config::CredentialStorageMode),
    EncryptedSecretPasswordChanged(String),
    EncryptedSecretConfirmChanged(String),
    UnlockEncryptedSecrets,
    ApplySecretStorageSelection,
    ClearConfigs,
    ConfigsCleared(Result<config::ClearConfigSummary, String>),
    AddCalendarPane,
    AddLiquidationsPane,
    AddTrackedTradesPane,
    AddOutcomesPane,
    AddTradingJournal,
    RefreshCalendar,
    CalendarLoaded(Result<Vec<api::CalendarEvent>, String>),
    CalendarImpactFilterChanged(CalendarImpactFilter),
    CalendarWindowFilterChanged(CalendarWindowFilter),
    Tick,
    ThemeChanged(String),
    MutedTickerInputChanged(String),
    MuteTicker,
    UnmuteTicker(String),
    MarketSlippageInputChanged(String),
    SaveMarketSlippage,
    ExecuteHotkey(config::HotkeyAction),
    StartRecordingHotkey(config::HotkeyAction),
    OpenWalletTrackerWindow,
    OpenWalletDetailsWindow(String),
    RefreshWalletDetails(window::Id),
    WalletDetailsLoaded(window::Id, String, Box<Result<WalletDetailsData, String>>),
    WalletDetailsWsUpdate(Option<String>, Box<WsUserData>),
    WindowOpened(window::Id),
    WindowClosed(window::Id),
    WindowResized(window::Id, Size),
    WindowMoved(window::Id, Point),
    // Trading Journal
    JournalFillsLoaded {
        account_key: Option<String>,
        address: String,
        result: Result<api::UserFillsPage, String>,
    },
    JournalRefresh,
    JournalEditStart(String, Option<String>),
    JournalEditCancel(String),
    JournalEditSave(String),
    JournalBufferChanged(String, bool, String),
    JournalFilterChanged(journal::JournalFilter),
    JournalSortChanged(journal::JournalSort),
    JournalToggleAllAssets,
    // Spaghetti chart
    SpaghettiSwitchTimeframe(SpaghettiChartId, Timeframe),
    SpaghettiReload(SpaghettiChartId),
    SpaghettiCandlesLoaded(SpaghettiCandleFetch, Result<Vec<Candle>, String>),
    SpaghettiWsCandleUpdate(SpaghettiChartId, String, Candle),
    SpaghettiOpenEditor(SpaghettiChartId),
    SpaghettiCloseEditor(SpaghettiChartId),
    SpaghettiEditorSearchChanged(SpaghettiChartId, String),
    SpaghettiAddSymbol(SpaghettiChartId, String),
    SpaghettiRemoveSymbol(SpaghettiChartId, String),
    SpaghettiSetSession(SpaghettiChartId, Option<spaghetti::Session>),
    SpaghettiSetSessionGranularityAuto(SpaghettiChartId),
    SpaghettiResetView(SpaghettiChartId),
    PairSetCandleMode(SpaghettiChartId, bool),
    WalletTrackerInputChanged(String),
    WalletTrackerLabelInputChanged(String),
    WalletTrackerAdd,
    WalletTrackerRemove(String),
    WalletTrackerLabelChanged(String, String),
    WalletTrackerRefresh,
    WalletTrackerRefreshDue,
    WalletTrackerRefreshOne(String),
    WalletTrackerRefreshOrdersDue,
    WalletTrackerRefreshOrders(String),
    WalletTrackerLoaded(String, Box<Result<WalletTrackerSnapshot, String>>),
    WalletTrackerOrdersLoaded(String, Box<Result<usize, String>>),
    RefreshPortfolio,
    PortfolioLoaded(String, Box<Result<PortfolioHistory, String>>),
    RefreshIncome,
    IncomeLoaded(String, Box<Result<IncomeSnapshot, String>>),
    ToggleIncomeAlerts,
    ToggleLiquidationAlerts,
    ToggleTrackedTradeAlerts,
    ToggleTrackedTradeAggregation,
    ToggleLiquidationFeedAggregation,
    ToggleLiquidationChart,
    ToggleLiquidationSummary,
    LiquidationAlertThresholdChanged(String),
    SaveLiquidationAlertThreshold,
    SetPortfolioScope(PortfolioScope),
    SetPortfolioWindow(PortfolioWindow),
    // Drawing tools
    SetDrawingTool(ChartId, Option<DrawingTool>),
    AddAnnotation(Annotation),
    RemoveAnnotation(AnnotationId),
    ClearDrawingTool,
    // Notifications
    DismissToast(u64),
    CopyToClipboard(String),
    TickToastCleanup,
    NoOp,
    SpinnerTick,
    StatusBarTick,
    ConfigSaved(Result<(), String>),
    ToggleSound,
    TestSound,
    ToggleDesktopNotifications,
    PlaceBuy,
    PlaceSell,
    OrderResult(Box<Result<ExchangeResponse, String>>),
    DismissOrderStatus,
    CancelOrder {
        coin: String,
        oid: u64,
    },
    CancelResult(Box<Result<ExchangeResponse, String>>),
    ToggleCloseMenu(String),
    ClosePosition {
        coin: String,
        fraction: f64,
        use_market: bool,
    },
    ClosePositionResult(Box<Result<ExchangeResponse, String>>),
    NukePositions,
    NukeResult(Box<Result<ExchangeResponse, String>>),
    StartChase(bool), // true = buy, false = sell
    StopChase,
    ChasePlaceResult(Box<Result<ExchangeResponse, String>>),
    ChaseCancelResult(Box<Result<ExchangeResponse, String>>),
    ChaseRestingOrder {
        coin: String,
        oid: u64,
        is_buy: bool,
        sz: f64,
        limit_px: f64,
    },
    // Per-chart messages (keyed by ChartId)
    ChartSwitchTimeframe(ChartId, Timeframe),
    ChartReload(ChartId),
    ChartResetView(ChartId),
    ChartCandlesLoaded(CandleFetchRequest, Result<Vec<Candle>, String>),
    ChartFundingHistoryLoaded(
        FundingFetchRequest,
        Box<Result<Vec<FundingRatePoint>, String>>,
    ),
    MacroCandlesLoaded(ChartId, String, Timeframe, Result<Vec<Candle>, String>),
    ChartWsCandleUpdate(ChartId, String, String, Candle),
    ChartWsAssetCtxUpdate(ChartId, String, AssetContext),
    ChartViewportChanged(ChartId, ChartViewport),
    ChartFundingPanelHeightChanged(ChartId, u16, bool),
    ToggleFundingRateDisplayMode(ChartId),
    FundingRefreshTick,
    ChartSymbolSelected(ChartId, String),
    ToggleChartInvert(ChartId),
    ChartOpenEditor(ChartId),
    ChartCloseEditor(ChartId),
    ChartEditorSearchChanged(ChartId, String),
    ChartEditorSubmit(ChartId),
    // Hotkeys related messages
    KeyboardEvent(iced::keyboard::Event, iced::event::Status),
    AddChart(pane_grid::Pane),
    ClosePane(pane_grid::Pane),
    ToggleHidePnl,
    // Quick order form (right-click on chart)
    OpenQuickOrder(ChartId, f64, f32, f32, f32, f32),
    QuickOrderQtyChanged(ChartId, String),
    QuickOrderToggleType(ChartId),
    CloseQuickOrder(ChartId),
    SubmitQuickOrder(ChartId, bool),
    QuickOrderResult(Box<Result<ExchangeResponse, String>>),
    EscapePressed,
    // Order drag-to-move (from chart canvas)
    MoveOrder {
        oid: u64,
        new_price: f64,
    },
    MoveOrderModifyResult {
        oid: u64,
        result: Box<Result<ExchangeResponse, String>>,
    },
    // Global messages
    SymbolsLoaded(Result<Vec<ExchangeSymbol>, String>),
    SymbolSearchChanged(String),
    SymbolSearchSortChanged(SymbolSearchSortMode),
    SymbolSearchMarketFilterChanged(SymbolSearchMarketFilter),
    SymbolSearchHip3DexFilterChanged(String),
    SymbolSearchContextsLoaded(
        u64,
        Result<HashMap<String, crate::api::WatchlistContext>, String>,
    ),
    SymbolSelected(String),
    BookLoaded(OrderBookId, Result<OrderBook, String>),
    WsBookUpdate(OrderBookId, String, OrderBook),
    OrderBookWsAssetCtxUpdate(OrderBookId, AssetContext),
    SetBookTickSize(OrderBookId, f64),
    CenterOrderBook(OrderBookId),
    ToggleOrderBookSettings(OrderBookId),
    ToggleOrderBookSpreadChart(OrderBookId),
    OrderBookSpreadChartResize(OrderBookId, f32),
    OrderBookSearchChanged(OrderBookId, String),
    OrderBookSetMode(OrderBookId, OrderBookSymbolMode),
    WalletKeyInputChanged(String),
    WalletAddressInputChanged(String),
    HydromancerKeyInputChanged(String),
    SaveHydromancerKey,
    ReconnectLiquidations,
    ReconnectTrackedTrades,
    WsHydromancerLiquidation(crate::ws::HydromancerWsMessage),
    WsHydromancerTrackedTrades(crate::ws::HydromancerWsMessage),
    ClearLiquidations,
    ClearTrackedTrades,
    ConnectWallet,
    DisconnectWallet,
    AccountDataLoaded(String, Box<Result<AccountData, String>>),
    RefreshAccountData,
    AllMidsBootstrapLoaded(String, Result<HashMap<String, f64>, String>),
    WsUserDataUpdate(Option<String>, Box<WsUserData>),
    // HyperDash liquidation heatmap
    HyperdashKeyInputChanged(String),
    SaveHyperdashKey,
    ToggleLiquidationOverlay(ChartId),
    ChartLiquidationLoaded(String, Box<Result<LiquidationLevel, String>>),
    RefreshLiquidations,
    // HyperDash historical liquidation heatmap
    ToggleHeatmapOverlay(ChartId),
    ChartHeatmapLoaded(String, Box<Result<LiquidationHeatmap, String>>),
    RefreshHeatmap,
}
