use crate::account::{AccountData, AssetContext, WalletDetailsData, WalletTrackerSnapshot};
use crate::account_analytics::{IncomeSnapshot, PortfolioHistory};
use crate::account_state::{BottomTab, PositionsSortColumn};
use crate::annotations::{Annotation, AnnotationId, DrawingTool};
use crate::api::{self, Candle, ExchangeSymbol, OrderBook};
use crate::calendar_state::{CalendarImpactFilter, CalendarWindowFilter};
use crate::chart::ChartViewport;
use crate::chart_screenshot::ChartScreenshotState;
use crate::chart_state::{CandleFetchRequest, ChartId, FundingFetchRequest};
use crate::config;
use crate::hydromancer_api::FundingRatePoint;
use crate::hyperdash_api::{LiquidationHeatmap, LiquidationLevel};
use crate::journal;
use crate::market_state::{
    LiveWatchlistId, OrderBookDisplayMode, OrderBookId, OrderBookSymbolMode,
    SymbolSearchMarketFilter, SymbolSearchSortMode,
};
use crate::pane_management::AddWidgetPlacement;
use crate::pnl_card::{PnlCardDisplayMode, PnlCardPercentMode, PnlCardTarget};
use crate::portfolio_state::{PnlValueDisplayMode, PortfolioScope, PortfolioWindow};
use crate::settings_state::SettingsTab;
use crate::signing::{ExchangeResponse, OrderKind};
use crate::spaghetti;
use crate::spaghetti_state::{SpaghettiCandleFetch, SpaghettiChartId};
use crate::timeframe::Timeframe;
use crate::ws::WsUserData;
use iced::widget::pane_grid;
use iced::{Point, Size, window};
use std::collections::HashMap;
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    SaveLayout(String),
    LoadLayout(config::SavedLayout),
    DeleteLayout(String),
    UpdateActiveLayout,
    LayoutRenameToggled(usize),
    LayoutRenameChanged(String),
    LayoutRenameSubmitted(usize),
    ExportLayout(config::SavedLayout),
    ImportLayout,
    LayoutImported(Result<config::SavedLayout, String>),
    LayoutExported(Result<(), String>),
    ExportWalletLabels,
    ImportWalletLabels,
    WalletLabelsExported(Result<(), String>),
    WalletLabelsImported(Result<config::WalletLabelsExport, String>),
    LayoutInputChanged(String),
    LiveWatchlistSearchChanged(LiveWatchlistId, String),
    LiveWatchlistContextsLoaded(
        u64,
        Result<HashMap<String, crate::api::WatchlistContext>, String>,
    ),
    LiveWatchlistHistoryLoaded(
        Vec<String>,
        u64,
        Result<HashMap<String, (f64, f64, f64)>, String>,
    ),
    LiveWatchlistAddSymbol(LiveWatchlistId, String),
    LiveWatchlistRemoveSymbol(LiveWatchlistId, String),
    LiveWatchlistRefreshTick,
    LiveWatchlistSortChanged(LiveWatchlistId, config::LiveWatchlistSortColumn),
    LiveWatchlistColumnToggled(LiveWatchlistId, config::LiveWatchlistColumn, bool),
    AddLiveWatchlistPane,
    AddOrderBookPane,
    AddAdvancedOrdersPane,
    PositionsSortChanged(PositionsSortColumn),

    ToggleAccountPicker,
    AccountPickerSelected(usize),
    AccountPickerRenameToggled(usize),
    AccountPickerLabelChanged(usize, String),
    AddAccount,
    GhostWallet(String),
    ForgetGhostAccount(usize),
    DeleteSavedAccount(usize),
    SaveCredentials,
    PaneResized(pane_grid::ResizeEvent),
    PaneDragged(pane_grid::DragEvent),
    PaneClicked(pane_grid::Pane),
    SwitchBottomTab(BottomTab),
    OrderPriceChanged(String),
    SetMidPrice,
    OrderBookPriceSelected {
        id: OrderBookId,
        price: String,
    },
    OrderQuantityChanged(String),
    SetOrderKind(OrderKind),
    ToggleOrderDenomination,
    OrderPercentageChanged(f32),
    ToggleReduceOnly,
    TogglePresetsMenu,
    TogglePresetCurrency,
    TogglePresetEditMode,
    SetAddWidgetPlacement(AddWidgetPlacement),
    EditPresetStart(crate::signing::OrderKind, usize, String),
    EditPresetChanged(String),
    EditPresetSave(crate::signing::OrderKind, usize),
    ExecutePreset(crate::signing::OrderKind, crate::config::OrderPreset, bool),
    ToggleFavourite(String),
    // Add widget menu
    ToggleAddWidgetMenu,
    ToggleLayoutMenu,
    ToggleMacroMenu(ChartId),
    ToggleMacroIndicator(ChartId, String),
    CloseAllMenus,
    AddPortfolioPane,
    AddIncomePane,
    AddComparisonChart,
    AddPairRatioChart,
    OpenSettingsWindow,
    SettingsTabSelected(SettingsTab),
    OpenUnlockCredentialsPopup,
    DismissUnlockCredentialsPopup,
    OpenCredentialStorageSettings,
    SecretStorageSelectionChanged(config::CredentialStorageMode),
    EncryptedSecretPasswordChanged(String),
    EncryptedSecretConfirmChanged(String),
    UnlockEncryptedSecrets,
    ApplySecretStorageSelection,
    ClearConfigs,
    ConfigsCleared(Result<config::ClearConfigSummary, String>),
    AddCalendarPane,
    AddLiquidationsPane,
    AddTrackedTradesPane,
    AddOutcomesPane,
    AddTradingJournal,
    RefreshCalendar,
    CalendarLoaded(Result<Vec<api::CalendarEvent>, String>),
    CalendarImpactFilterChanged(CalendarImpactFilter),
    CalendarWindowFilterChanged(CalendarWindowFilter),
    Tick,
    ThemeChanged(String),
    PaneBorderThicknessChanged(f32),
    PaneCornerRadiusChanged(f32),
    MutedTickerInputChanged(String),
    MuteTicker,
    UnmuteTicker(String),
    MarketUniverseChanged(config::MarketUniverseConfig),
    MarketSlippageInputChanged(String),
    SaveMarketSlippage,
    ExecuteHotkey(config::HotkeyAction),
    StartRecordingHotkey(config::HotkeyAction),
    OpenWalletTrackerWindow,
    OpenWalletDetailsWindow(String),
    RefreshWalletDetails(window::Id),
    WalletDetailsLoaded(window::Id, String, Box<Result<WalletDetailsData, String>>),
    WalletDetailsWsUpdate(Option<String>, Box<WsUserData>),
    WindowOpened(window::Id),
    WindowClosed(window::Id),
    WindowResized(window::Id, Size),
    WindowMoved(window::Id, Point),
    // Trading Journal
    JournalFillsLoaded {
        account_key: Option<String>,
        address: String,
        result: Result<api::UserFillsPage, String>,
    },
    JournalRefresh,
    JournalEditStart(String, Option<String>),
    JournalEditCancel(String),
    JournalEditSave(String),
    JournalBufferChanged(String, bool, String),
    JournalFilterChanged(journal::JournalFilter),
    JournalSortChanged(journal::JournalSort),
    JournalToggleAllAssets,
    // Spaghetti chart
    SpaghettiSwitchTimeframe(SpaghettiChartId, Timeframe),
    SpaghettiReload(SpaghettiChartId),
    SpaghettiCandlesLoaded(SpaghettiCandleFetch, Result<Vec<Candle>, String>),
    SpaghettiWsCandleUpdate(SpaghettiChartId, String, Candle),
    SpaghettiOpenEditor(SpaghettiChartId),
    SpaghettiCloseEditor(SpaghettiChartId),
    SpaghettiEditorSearchChanged(SpaghettiChartId, String),
    SpaghettiAddSymbol(SpaghettiChartId, String),
    SpaghettiRemoveSymbol(SpaghettiChartId, String),
    SpaghettiSetSession(SpaghettiChartId, Option<spaghetti::Session>),
    SpaghettiSetSessionGranularityAuto(SpaghettiChartId),
    SpaghettiResetView(SpaghettiChartId),
    ToggleSpaghettiStyleMenu(SpaghettiChartId),
    ToggleSpaghettiLabels(SpaghettiChartId),
    SpaghettiSetColorMode(SpaghettiChartId, spaghetti::ComparisonColorMode),
    PairSetCandleMode(SpaghettiChartId, bool),
    WalletTrackerInputChanged(String),
    WalletTrackerLabelInputChanged(String),
    WalletTrackerAdd,
    WalletTrackerRemove(String),
    WalletTrackerLabelChanged(String, String),
    WalletTrackerRefresh,
    WalletTrackerRefreshDue,
    WalletTrackerRefreshOne(String),
    WalletTrackerRefreshOrdersDue,
    WalletTrackerRefreshOrders(String),
    WalletTrackerLoaded(String, Box<Result<WalletTrackerSnapshot, String>>),
    WalletTrackerOrdersLoaded(String, Box<Result<usize, String>>),
    RefreshPortfolio,
    PortfolioLoaded(String, Box<Result<PortfolioHistory, String>>),
    RefreshIncome,
    IncomeLoaded(String, Box<Result<IncomeSnapshot, String>>),
    ToggleIncomeAlerts,
    ToggleLiquidationAlerts,
    ToggleTrackedTradeAlerts,
    ToggleTrackedTradeAggregation,
    ToggleTrackedTradeSettingsMenu,
    ToggleLiquidationFeedAggregation,
    ToggleLiquidationChart,
    ToggleLiquidationSummary,
    ToggleLiquidationSettingsMenu,
    LiquidationAlertThresholdChanged(String),
    SaveLiquidationAlertThreshold,
    SetPortfolioPnlValueMode(PnlValueDisplayMode),
    SetPortfolioScope(PortfolioScope),
    SetPortfolioWindow(PortfolioWindow),
    // Drawing tools
    SetDrawingTool(ChartId, Option<DrawingTool>),
    AddAnnotation(Annotation),
    RemoveAnnotation(AnnotationId),
    ClearDrawingTool,
    // Notifications
    DismissToast(u64),
    CopyToClipboard(String),
    TickToastCleanup,
    NoOp,
    SpinnerTick,
    StatusBarTick,
    ConfigSaved(Result<(), String>),
    ToggleSound,
    ToggleDesktopNotifications,
    PlaceBuy,
    PlaceSell,
    OrderResult(Box<Result<ExchangeResponse, String>>),
    DismissOrderStatus,
    CancelOrder {
        coin: String,
        oid: u64,
    },
    CancelResult(Box<Result<ExchangeResponse, String>>),
    ToggleCloseMenu(String),
    ToggleHiddenPosition(String),
    ToggleShowHiddenPositions,
    OpenPnlCard(PnlCardTarget),
    SetPnlCardDisplayMode(window::Id, PnlCardDisplayMode),
    SetPnlCardPercentMode(window::Id, PnlCardPercentMode),
    TogglePnlCardPricePrivacy(window::Id, bool),
    TogglePnlCardPositionSize(window::Id, bool),
    CopyPnlCard(window::Id),
    PnlCardCopied(Result<(), String>),
    SavePnlCard(window::Id),
    PnlCardSaved(Result<Option<PathBuf>, String>),
    ClosePosition {
        coin: String,
        fraction: f64,
        use_market: bool,
    },
    ClosePositionResult(Box<Result<ExchangeResponse, String>>),
    NukePositions,
    NukeResult(Box<Result<ExchangeResponse, String>>),
    StartChase(bool), // true = buy, false = sell
    StopChase,
    StopChaseById(u64),
    StopAllAdvancedOrders,
    TwapDurationChanged(String),
    TwapSlicesChanged(String),
    TwapMinPriceChanged(String),
    TwapMaxPriceChanged(String),
    TwapRandomizeToggled(bool),
    StartTwap(bool), // true = buy, false = sell
    StopTwap(u64),
    TwapTick,
    TwapBookUpdate {
        twap_id: u64,
        coin: String,
        book: OrderBook,
    },
    TwapSliceResult {
        twap_id: u64,
        result: Box<Result<ExchangeResponse, String>>,
    },
    TwapUnexpectedCancelResult {
        twap_id: u64,
        oid: Option<u64>,
        cloid: Option<String>,
        result: Box<Result<ExchangeResponse, String>>,
    },
    TwapOrderStatusLoaded {
        twap_id: u64,
        cloid: String,
        result: Box<Result<api::OrderStatusResult, String>>,
    },
    OpenTwapDetails(u64),
    OpenAdvancedOrderHistory(String),
    ChaseInitialBookLoaded {
        chase_id: u64,
        result: Box<Result<OrderBook, String>>,
    },
    ChaseBookUpdate {
        chase_id: u64,
        coin: String,
        book: OrderBook,
    },
    ChaseRepriceTick,
    ChasePlaceResult {
        chase_id: u64,
        result: Box<Result<ExchangeResponse, String>>,
    },
    ChaseCancelResult {
        chase_id: u64,
        oid: u64,
        result: Box<Result<ExchangeResponse, String>>,
    },
    ChaseRestingOrder {
        coin: String,
        oid: u64,
        is_buy: bool,
        sz: f64,
        limit_px: f64,
        reduce_only: Option<bool>,
    },
    // Per-chart messages (keyed by ChartId)
    ChartSwitchTimeframe(ChartId, Timeframe),
    ChartReload(ChartId),
    ChartResetView(ChartId),
    ChartCandlesLoaded(CandleFetchRequest, Result<Vec<Candle>, String>),
    ChartFundingHistoryLoaded(
        FundingFetchRequest,
        Box<Result<Vec<FundingRatePoint>, String>>,
    ),
    MacroCandlesLoaded(ChartId, String, Timeframe, Result<Vec<Candle>, String>),
    ChartWsCandleUpdate(ChartId, String, String, Candle),
    ChartPriceFlashTick,
    ChartWsAssetCtxUpdate(ChartId, String, AssetContext),
    ChartViewportChanged(ChartId, ChartViewport),
    ChartFundingPanelHeightChanged(ChartId, u16, bool),
    ToggleFundingRateDisplayMode(ChartId),
    FundingRefreshTick,
    ToggleOpenInterestNotional(ChartId),
    ChartSymbolSelected(ChartId, String),
    ToggleChartInvert(ChartId),
    ToggleChartTradeMarkers(ChartId),
    ChartOpenEditor(ChartId),
    ChartCloseEditor(ChartId),
    ChartEditorSearchChanged(ChartId, String),
    ChartEditorSubmit(ChartId),
    ToggleChartScreenshotMenu(ChartId),
    ToggleChartScreenshotObscurePositionEntry(bool),
    ToggleChartScreenshotHidePositionsAndOrders(bool),
    OpenChartScreenshot(ChartId),
    ChartScreenshotBoundsResolved(u64, ChartId, Option<iced::Rectangle>),
    ChartScreenshotCaptured(u64, ChartId, Result<ChartScreenshotState, String>),
    CopyChartScreenshot,
    ChartScreenshotCopied(Result<(), String>),
    SaveChartScreenshot,
    ChartScreenshotSaved(Result<Option<PathBuf>, String>),
    CloseChartScreenshotWindow,
    // Hotkeys related messages
    KeyboardEvent(iced::keyboard::Event, iced::event::Status),
    AddChart(pane_grid::Pane),
    ClosePane(pane_grid::Pane),
    ToggleHidePnl,
    // Quick order form (right-click on chart)
    OpenQuickOrder(ChartId, f64, f32, f32, f32, f32),
    QuickOrderQtyChanged(ChartId, String),
    QuickOrderPercentageChanged(ChartId, f32),
    QuickOrderToggleDenomination(ChartId),
    QuickOrderToggleType(ChartId),
    CloseQuickOrder(ChartId),
    SubmitQuickOrder(ChartId, bool),
    QuickOrderResult(Box<Result<ExchangeResponse, String>>),
    EscapePressed,
    // Order drag-to-move (from chart canvas)
    MoveOrderDragStarted {
        oid: u64,
    },
    MoveOrder {
        oid: u64,
        new_price: f64,
    },
    MoveOrderModifyResult {
        oid: u64,
        result: Box<Result<ExchangeResponse, String>>,
    },
    // Global messages
    SymbolsLoaded(Result<Vec<ExchangeSymbol>, String>),
    SymbolSearchChanged(String),
    SymbolSearchSortChanged(SymbolSearchSortMode),
    SymbolSearchMarketFilterChanged(SymbolSearchMarketFilter),
    SymbolSearchHip3DexFilterChanged(String),
    SymbolSearchContextsLoaded(
        u64,
        Result<HashMap<String, crate::api::WatchlistContext>, String>,
    ),
    SymbolSelected(String),
    BookLoaded {
        id: OrderBookId,
        coin: String,
        tick_size: f64,
        sigfigs: (Option<u8>, Option<u8>),
        result: Result<OrderBook, String>,
    },
    WsBookUpdate {
        id: OrderBookId,
        coin: String,
        sigfigs: (Option<u8>, Option<u8>),
        book: OrderBook,
    },
    OrderBookWsAssetCtxUpdate(OrderBookId, AssetContext),
    SetBookTickSize(OrderBookId, f64),
    ToggleOrderBookCenterOnMid(OrderBookId),
    ToggleOrderBookSettings(OrderBookId),
    ToggleOrderBookSpreadChart(OrderBookId),
    OrderBookSpreadChartResize(OrderBookId, f32),
    OrderBookSearchChanged(OrderBookId, String),
    OrderBookSetMode(OrderBookId, OrderBookSymbolMode),
    SetOrderBookDisplayMode(OrderBookId, OrderBookDisplayMode),
    WalletKeyInputChanged(String),
    WalletAddressInputChanged(String),
    HydromancerKeyInputChanged(String),
    SaveHydromancerKey,
    ReconnectLiquidations,
    ReconnectTrackedTrades,
    WsHydromancerLiquidation(crate::ws::HydromancerWsMessage),
    WsHydromancerTrackedTrades(crate::ws::HydromancerWsMessage),
    ClearLiquidations,
    ClearTrackedTrades,
    ConnectWallet,
    DisconnectWallet,
    AccountDataLoaded(String, Box<Result<AccountData, String>>),
    RefreshAccountData,
    AllMidsBootstrapLoaded(String, Result<HashMap<String, f64>, String>),
    WsUserDataUpdate(Option<String>, Box<WsUserData>),
    // HyperDash liquidation heatmap
    HyperdashKeyInputChanged(String),
    SaveHyperdashKey,
    ToggleLiquidationOverlay(ChartId),
    ChartLiquidationLoaded(String, Box<Result<LiquidationLevel, String>>),
    RefreshLiquidations,
    // HyperDash historical liquidation heatmap
    ToggleHeatmapOverlay(ChartId),
    ChartHeatmapLoaded(String, Box<Result<LiquidationHeatmap, String>>),
    RefreshHeatmap,
}
